package pgerror

import (
	"testing"

	"github.com/lib/pq"
)

func TestErrorFuncs(t *testing.T) {

	for code, message := range errorCodeNames {

		check, ok := errorCodeFuncs[message]
		if !ok {
			t.Fatalf("Missing error helper function: %s", message)
		}

		var err error = &pq.Error{Code: code, Message: message}

		if check(err) == nil {
			t.Fatalf("Error checker failed for error %s (%s)", code, message)
		}
	}
}

func TestErrorFuncsNegative(t *testing.T) {

	var code pq.ErrorCode = "code-unicorn"
	var err error = pq.Error{Code: code, Message: "does not exist at all"}

	for message, check := range errorCodeFuncs {
		if check(err) != nil {
			t.Fatalf("Error Check for `%s` returned true for invalid error: %s", message, code)
		}
	}

}

var errorCodeFuncs = map[string]func(error) *pq.Error{
	"successful_completion":                 SuccessfulCompletion,
	"warning":                               Warning,
	"dynamic_result_sets_returned":          DynamicResultSetsReturned,
	"implicit_zero_bit_padding":             ImplicitZeroBitPadding,
	"null_value_eliminated_in_set_function": NullValueEliminatedInSetFunction,
	"privilege_not_granted":                 PrivilegeNotGranted,
	"privilege_not_revoked":                 PrivilegeNotRevoked,
	"string_data_right_truncation":          StringDataRightTruncation,
	"deprecated_feature":                    DeprecatedFeature,
	"no_data":                               NoData,
	"no_additional_dynamic_result_sets_returned":           NoAdditionalDynamicResultSetsReturned,
	"sql_statement_not_yet_complete":                       SQLStatementNotYetComplete,
	"connection_exception":                                 ConnectionException,
	"connection_does_not_exist":                            ConnectionDoesNotExist,
	"connection_failure":                                   ConnectionFailure,
	"sqlclient_unable_to_establish_sqlconnection":          SQLclientUnableToEstablishSQLconnection,
	"sqlserver_rejected_establishment_of_sqlconnection":    SQLserverRejectedEstablishmentOfSQLconnection,
	"transaction_resolution_unknown":                       TransactionResolutionUnknown,
	"protocol_violation":                                   ProtocolViolation,
	"triggered_action_exception":                           TriggeredActionException,
	"feature_not_supported":                                FeatureNotSupported,
	"invalid_transaction_initiation":                       InvalidTransactionInitiation,
	"locator_exception":                                    LocatorException,
	"invalid_locator_specification":                        InvalidLocatorSpecification,
	"invalid_grantor":                                      InvalidGrantor,
	"invalid_grant_operation":                              InvalidGrantOperation,
	"invalid_role_specification":                           InvalidRoleSpecification,
	"diagnostics_exception":                                DiagnosticsException,
	"stacked_diagnostics_accessed_without_active_handler":  StackedDiagnosticsAccessedWithoutActiveHandler,
	"case_not_found":                                       CaseNotFound,
	"cardinality_violation":                                CardinalityViolation,
	"data_exception":                                       DataException,
	"array_subscript_error":                                ArraySubscriptError,
	"character_not_in_repertoire":                          CharacterNotInRepertoire,
	"datetime_field_overflow":                              DatetimeFieldOverflow,
	"division_by_zero":                                     DivisionByZero,
	"error_in_assignment":                                  ErrorInAssignment,
	"escape_character_conflict":                            EscapeCharacterConflict,
	"indicator_overflow":                                   IndicatorOverflow,
	"interval_field_overflow":                              IntervalFieldOverflow,
	"invalid_argument_for_logarithm":                       InvalidArgumentForLogarithm,
	"invalid_argument_for_ntile_function":                  InvalidArgumentForNtileFunction,
	"invalid_argument_for_nth_value_function":              InvalidArgumentForNthValueFunction,
	"invalid_argument_for_power_function":                  InvalidArgumentForPowerFunction,
	"invalid_argument_for_width_bucket_function":           InvalidArgumentForWidthBucketFunction,
	"invalid_character_value_for_cast":                     InvalidCharacterValueForCast,
	"invalid_datetime_format":                              InvalidDatetimeFormat,
	"invalid_escape_character":                             InvalidEscapeCharacter,
	"invalid_escape_octet":                                 InvalidEscapeOctet,
	"invalid_escape_sequence":                              InvalidEscapeSequence,
	"nonstandard_use_of_escape_character":                  NonstandardUseOfEscapeCharacter,
	"invalid_indicator_parameter_value":                    InvalidIndicatorParameterValue,
	"invalid_parameter_value":                              InvalidParameterValue,
	"invalid_regular_expression":                           InvalidRegularExpression,
	"invalid_row_count_in_limit_clause":                    InvalidRowCountInLimitClause,
	"invalid_row_count_in_result_offset_clause":            InvalidRowCountInResultOffsetClause,
	"invalid_time_zone_displacement_value":                 InvalidTimeZoneDisplacementValue,
	"invalid_use_of_escape_character":                      InvalidUseOfEscapeCharacter,
	"most_specific_type_mismatch":                          MostSpecificTypeMismatch,
	"null_value_not_allowed":                               NullValueNotAllowed,
	"null_value_no_indicator_parameter":                    NullValueNoIndicatorParameter,
	"numeric_value_out_of_range":                           NumericValueOutOfRange,
	"string_data_length_mismatch":                          StringDataLengthMismatch,
	"substring_error":                                      SubstringError,
	"trim_error":                                           TrimError,
	"unterminated_c_string":                                UnterminatedCString,
	"zero_length_character_string":                         ZeroLengthCharacterString,
	"floating_point_exception":                             FloatingPointException,
	"invalid_text_representation":                          InvalidTextRepresentation,
	"invalid_binary_representation":                        InvalidBinaryRepresentation,
	"bad_copy_file_format":                                 BadCopyFileFormat,
	"untranslatable_character":                             UntranslatableCharacter,
	"not_an_xml_document":                                  NotAnXMLDocument,
	"invalid_xml_document":                                 InvalidXMLDocument,
	"invalid_xml_content":                                  InvalidXMLContent,
	"invalid_xml_comment":                                  InvalidXMLComment,
	"invalid_xml_processing_instruction":                   InvalidXMLProcessingInstruction,
	"integrity_constraint_violation":                       IntegrityConstraintViolation,
	"restrict_violation":                                   RestrictViolation,
	"not_null_violation":                                   NotNullViolation,
	"foreign_key_violation":                                ForeignKeyViolation,
	"unique_violation":                                     UniqueViolation,
	"check_violation":                                      CheckViolation,
	"exclusion_violation":                                  ExclusionViolation,
	"invalid_cursor_state":                                 InvalidCursorState,
	"invalid_transaction_state":                            InvalidTransactionState,
	"active_sql_transaction":                               ActiveSQLTransaction,
	"branch_transaction_already_active":                    BranchTransactionAlreadyActive,
	"held_cursor_requires_same_isolation_level":            HeldCursorRequiresSameIsolationLevel,
	"inappropriate_access_mode_for_branch_transaction":     InappropriateAccessModeForBranchTransaction,
	"inappropriate_isolation_level_for_branch_transaction": InappropriateIsolationLevelForBranchTransaction,
	"no_active_sql_transaction_for_branch_transaction":     NoActiveSQLTransactionForBranchTransaction,
	"read_only_sql_transaction":                            ReadOnlySQLTransaction,
	"schema_and_data_statement_mixing_not_supported":       SchemaAndDataStatementMixingNotSupported,
	"no_active_sql_transaction":                            NoActiveSQLTransaction,
	"in_failed_sql_transaction":                            InFailedSQLTransaction,
	"invalid_sql_statement_name":                           InvalidSQLStatementName,
	"triggered_data_change_violation":                      TriggeredDataChangeViolation,
	"invalid_authorization_specification":                  InvalidAuthorizationSpecification,
	"invalid_password":                                     InvalidPassword,
	"dependent_privilege_descriptors_still_exist":          DependentPrivilegeDescriptorsStillExist,
	"dependent_objects_still_exist":                        DependentObjectsStillExist,
	"invalid_transaction_termination":                      InvalidTransactionTermination,
	"sql_routine_exception":                                SQLRoutineException,
	"function_executed_no_return_statement":                FunctionExecutedNoReturnStatement,
	"modifying_sql_data_not_permitted":                     ModifyingSQLDataNotPermitted,
	"prohibited_sql_statement_attempted":                   ProhibitedSQLStatementAttempted,
	"reading_sql_data_not_permitted":                       ReadingSQLDataNotPermitted,
	"invalid_cursor_name":                                  InvalidCursorName,
	"external_routine_exception":                           ExternalRoutineException,
	"containing_sql_not_permitted":                         ContainingSQLNotPermitted,
	"external_routine_invocation_exception":                ExternalRoutineInvocationException,
	"invalid_sqlstate_returned":                            InvalidSQLstateReturned,
	"trigger_protocol_violated":                            TriggerProtocolViolated,
	"srf_protocol_violated":                                SrfProtocolViolated,
	"savepoint_exception":                                  SavepointException,
	"invalid_savepoint_specification":                      InvalidSavepointSpecification,
	"invalid_catalog_name":                                 InvalidCatalogName,
	"invalid_schema_name":                                  InvalidSchemaName,
	"transaction_rollback":                                 TransactionRollback,
	"transaction_integrity_constraint_violation":           TransactionIntegrityConstraintViolation,
	"serialization_failure":                                SerializationFailure,
	"statement_completion_unknown":                         StatementCompletionUnknown,
	"deadlock_detected":                                    DeadlockDetected,
	"syntax_error_or_access_rule_violation":                SyntaxErrorOrAccessRuleViolation,
	"syntax_error":                                         SyntaxError,
	"insufficient_privilege":                               InsufficientPrivilege,
	"cannot_coerce":                                        CannotCoerce,
	"grouping_error":                                       GroupingError,
	"windowing_error":                                      WindowingError,
	"invalid_recursion":                                    InvalidRecursion,
	"invalid_foreign_key":                                  InvalidForeignKey,
	"invalid_name":                                         InvalidName,
	"name_too_long":                                        NameTooLong,
	"reserved_name":                                        ReservedName,
	"datatype_mismatch":                                    DatatypeMismatch,
	"indeterminate_datatype":                               IndeterminateDatatype,
	"collation_mismatch":                                   CollationMismatch,
	"indeterminate_collation":                              IndeterminateCollation,
	"wrong_object_type":                                    WrongObjectType,
	"undefined_column":                                     UndefinedColumn,
	"undefined_function":                                   UndefinedFunction,
	"undefined_table":                                      UndefinedTable,
	"undefined_parameter":                                  UndefinedParameter,
	"undefined_object":                                     UndefinedObject,
	"duplicate_column":                                     DuplicateColumn,
	"duplicate_cursor":                                     DuplicateCursor,
	"duplicate_database":                                   DuplicateDatabase,
	"duplicate_function":                                   DuplicateFunction,
	"duplicate_prepared_statement":                         DuplicatePreparedStatement,
	"duplicate_schema":                                     DuplicateSchema,
	"duplicate_table":                                      DuplicateTable,
	"duplicate_alias":                                      DuplicateAlias,
	"duplicate_object":                                     DuplicateObject,
	"ambiguous_column":                                     AmbiguousColumn,
	"ambiguous_function":                                   AmbiguousFunction,
	"ambiguous_parameter":                                  AmbiguousParameter,
	"ambiguous_alias":                                      AmbiguousAlias,
	"invalid_column_reference":                             InvalidColumnReference,
	"invalid_column_definition":                            InvalidColumnDefinition,
	"invalid_cursor_definition":                            InvalidCursorDefinition,
	"invalid_database_definition":                          InvalidDatabaseDefinition,
	"invalid_function_definition":                          InvalidFunctionDefinition,
	"invalid_prepared_statement_definition":                InvalidPreparedStatementDefinition,
	"invalid_schema_definition":                            InvalidSchemaDefinition,
	"invalid_table_definition":                             InvalidTableDefinition,
	"invalid_object_definition":                            InvalidObjectDefinition,
	"with_check_option_violation":                          WithCheckOptionViolation,
	"insufficient_resources":                               InsufficientResources,
	"disk_full":                                            DiskFull,
	"out_of_memory":                                        OutOfMemory,
	"too_many_connections":                                 TooManyConnections,
	"configuration_limit_exceeded":                         ConfigurationLimitExceeded,
	"program_limit_exceeded":                               ProgramLimitExceeded,
	"statement_too_complex":                                StatementTooComplex,
	"too_many_columns":                                     TooManyColumns,
	"too_many_arguments":                                   TooManyArguments,
	"object_not_in_prerequisite_state":                     ObjectNotInPrerequisiteState,
	"object_in_use":                                        ObjectInUse,
	"cant_change_runtime_param":                            CantChangeRuntimeParam,
	"lock_not_available":                                   LockNotAvailable,
	"operator_intervention":                                OperatorIntervention,
	"query_canceled":                                       QueryCanceled,
	"admin_shutdown":                                       AdminShutdown,
	"crash_shutdown":                                       CrashShutdown,
	"cannot_connect_now":                                   CannotConnectNow,
	"database_dropped":                                     DatabaseDropped,
	"system_error":                                         SystemError,
	"io_error":                                             IoError,
	"undefined_file":                                       UndefinedFile,
	"duplicate_file":                                       DuplicateFile,
	"config_file_error":                                    ConfigFileError,
	"lock_file_exists":                                     LockFileExists,
	"fdw_error":                                            FdwError,
	"fdw_column_name_not_found":                            FdwColumnNameNotFound,
	"fdw_dynamic_parameter_value_needed":                   FdwDynamicParameterValueNeeded,
	"fdw_function_sequence_error":                          FdwFunctionSequenceError,
	"fdw_inconsistent_descriptor_information":              FdwInconsistentDescriptorInformation,
	"fdw_invalid_attribute_value":                          FdwInvalidAttributeValue,
	"fdw_invalid_column_name":                              FdwInvalidColumnName,
	"fdw_invalid_column_number":                            FdwInvalidColumnNumber,
	"fdw_invalid_data_type":                                FdwInvalidDataType,
	"fdw_invalid_data_type_descriptors":                    FdwInvalidDataTypeDescriptors,
	"fdw_invalid_descriptor_field_identifier":              FdwInvalidDescriptorFieldIdentifier,
	"fdw_invalid_handle":                                   FdwInvalidHandle,
	"fdw_invalid_option_index":                             FdwInvalidOptionIndex,
	"fdw_invalid_option_name":                              FdwInvalidOptionName,
	"fdw_invalid_string_length_or_buffer_length":           FdwInvalidStringLengthOrBufferLength,
	"fdw_invalid_string_format":                            FdwInvalidStringFormat,
	"fdw_invalid_use_of_null_pointer":                      FdwInvalidUseOfNullPointer,
	"fdw_too_many_handles":                                 FdwTooManyHandles,
	"fdw_out_of_memory":                                    FdwOutOfMemory,
	"fdw_no_schemas":                                       FdwNoSchemas,
	"fdw_option_name_not_found":                            FdwOptionNameNotFound,
	"fdw_reply_handle":                                     FdwReplyHandle,
	"fdw_schema_not_found":                                 FdwSchemaNotFound,
	"fdw_table_not_found":                                  FdwTableNotFound,
	"fdw_unable_to_create_execution":                       FdwUnableToCreateExecution,
	"fdw_unable_to_create_reply":                           FdwUnableToCreateReply,
	"fdw_unable_to_establish_connection":                   FdwUnableToEstablishConnection,
	"plpgsql_error":                                        PlpgsqlError,
	"raise_exception":                                      RaiseException,
	"no_data_found":                                        NoDataFound,
	"too_many_rows":                                        TooManyRows,
	"internal_error":                                       InternalError,
	"data_corrupted":                                       DataCorrupted,
	"index_corrupted":                                      IndexCorrupted,
}
